version: '3'
services:
  spring-boot-demo-01:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/fengxin58/spring-boot-demo:0.0.1.RELEASE
    ports:
    - 60001:60001/tcp
    environment:
      server-profile=prod
      server-port=60001
      server-name=demo-prod
    restart: always
    labels:
      aliyun.scale: '1'
      aliyun.lb.port_60001: http://ebus:60001
